[log_file]
# Log file path. Leaving this blank will only log to the console.
path = ""
# File log level. Valid values are "off", "trace", "debug", "info", "warning", "error" and "critical". 
log_level = "trace"


[console]
# Console log level. Valid values are "off", "trace", "debug", "info", "warning", "error" and "critical". 
log_level = "debug" 
# If true, prints the original address of instructions as if the game was unpatched. Otherwise, prints
# the real memory address of the instruction, which may have been relocated due to previous patches.
print_original_addresses = true 
# If true, will still print a message to the console when another instruction accesses a field and deduces the
# same type as previous ones. You may want to disable this if you only want to see actual field type updates.  
print_upheld_fields = true


[dumps]
# Interval, in milliseconds, between file dumps.
interval = 10000
# If true, will create a CSV file storing param accesses by SIMD instructions which have been ignored 
# by the field type deductor.
dump_simd_accesses = true
# If true, dumps the original address of instructions as if the game was unpatched. Otherwise, dumps
# the real memory address of the instruction, which may have been relocated due to previous patches.
dump_original_addresses = true


[defs.parsing]
# Regex used to determine if a field should be considered unknown/unamed and thus
# susceptible to type overrules via automatic deduction
unnamed_field_regex = "^unk_.*"
# Regex used to determine if a field should be considered "untyped memory" and thus 
# ignored 
untyped_memory_regex = "^untyped_.*"
# If true, will ignore comments (and thus delete them when reserializing) 
ignore_comments = false
# If true, will ignore param types (and thus use the ones in param files instead), defaulting
# to the param name if not present
ignore_param_types = false


[defs.serialization]
# If true, Information about field conflicts will be added as a comment before the field XML node
conflict_comments = true
# Type prefix (i.e. "s" for s8/s16/s32/etc) used for integers whose signedness could not be deduced. 
# Can be used to default to a particular signedness, or use a new type entirely for more information.
unk_int_prefix = "s"